[package]
name = "razor_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"

[build-dependencies]
cc = "1.0"
bindgen = "0.59"

[dev-dependencies]
tokio = { version = "1.38", features = ["full"] }
env_logger = "0.10"